### ISSUE TITLE
Version mismatch of wasm-bindgen

### ISSUE THREAD

**Issue by xTeKc** [DioxusLabs/dioxus#1613] opened 2023-11-06 00:44 UTC
**Problem**
I encountered an issue when trying to use the dioxus-cli tool. The version of wasm-bindgen specified in the root Cargo.toml file is 0.2.87, but the wasm-bindgen version used during the build process is 0.2.88. This version mismatch is causing the error. The only dependencies used in the project are `dioxus = "0.4.0"` and `dioxus-web = "0.4.0"`.

**Steps To Reproduce**

-  cargo install dioxus-cli --locked
- dx serve --hot-reload

**Expected behavior**

To serve the Dioxus web app with full featured hot reloading.

**Screenshots**

![dx-output](https://github.com/DioxusLabs/dioxus/assets/81730792/10ae5b34-c276-42d9-be84-63de1e61f96a)

**Environment:**
 - Dioxus CLI version: [`0.4.1`]
 - Rust version: [`1.70.0`, `stable`]
 - OS info: [`Linux 6.5.8`, `Fedora 38`]
 - App platform: [`web`]

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [x] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jacobsvante** [comment] 2023-11-06 11:36
Same issue here.

@jkelleyrtp Could this be related to that the dioxus crate has not been updated to 0.4.1 whilst the dioxus-cli crate has?

**Comment by jacobsvante** [comment] 2023-11-06 11:43
@ealmloff I can see that you published 0.4.1 on github so copying in you here as well.

**Comment by ealmloff** [comment] 2023-11-06 13:55
This is a duplicate of https://github.com/DioxusLabs/dioxus/issues/1601. If you install the CLI without the locked flag (as the documentation was updated in https://github.com/DioxusLabs/docsite/pull/153 to suggest) it should fix this issue

**Comment by jacobsvante** [comment] 2023-11-06 15:04
That did the trick, yay!

**Comment by xTeKc** [comment] 2023-11-06 18:13
> This is a duplicate of #1601. If you install the CLI without the locked flag (as the documentation was updated in [DioxusLabs/docsite#153](https://github.com/DioxusLabs/docsite/pull/153) to suggest) it should fix this issue

Whoops, forgot to search for related issues first. But, the `--locked` still remains in `packages/cli` which is where I was reading. New PR incoming.

**Closed** 2023-11-06 19:32 UTC
