### ISSUE TITLE
Multiple Issue of DX Cli on Mac M1

### ISSUE THREAD

**Issue by codeitlikemiley** [DioxusLabs/dioxus#1425] opened 2023-09-04 02:42 UTC
Hi im using a Mac M1 

i tried to install dioxus-cli 
```
cargo install dioxus-cli
```

but got this error
<details>
<summary>Error Details</summary>

<code>
    Updating crates.io index
  Installing dioxus-cli v0.4.0
    Updating crates.io index
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling libc v0.2.147
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling memchr v2.6.3
   Compiling serde v1.0.188
   Compiling version_check v0.9.4
   Compiling value-bag v1.4.1
   Compiling log v0.4.20
   Compiling once_cell v1.18.0
   Compiling scopeguard v1.2.0
   Compiling thiserror v1.0.48
   Compiling smallvec v1.11.0
   Compiling lock_api v0.4.10
   Compiling quote v1.0.33
   Compiling jobserver v0.1.26
   Compiling itoa v1.0.9
   Compiling syn v2.0.31
   Compiling cc v1.0.83
   Compiling parking_lot_core v0.9.8
   Compiling futures-core v0.3.28
   Compiling syn v1.0.109
   Compiling getrandom v0.2.10
   Compiling pin-project-lite v0.2.13
   Compiling pkg-config v0.3.27
   Compiling futures-sink v0.3.28
   Compiling bitflags v2.4.0
   Compiling parking_lot v0.12.1
   Compiling futures-io v0.3.28
   Compiling bitflags v1.3.2
   Compiling num_cpus v1.16.0
   Compiling slab v0.4.9
   Compiling futures-task v0.3.28
   Compiling futures-channel v0.3.28
   Compiling bytes v1.4.0
   Compiling futures-util v0.3.28
   Compiling pin-utils v0.1.0
   Compiling fnv v1.0.7
   Compiling rustix v0.38.11
   Compiling errno v0.3.3
   Compiling ppv-lite86 v0.2.17
   Compiling num-traits v0.2.16
   Compiling aho-corasick v1.0.5
   Compiling ahash v0.7.6
   Compiling regex-syntax v0.7.5
   Compiling siphasher v0.3.11
   Compiling getrandom v0.1.16
   Compiling mio v0.8.8
   Compiling socket2 v0.5.3
   Compiling signal-hook-registry v1.4.1
   Compiling typenum v1.16.0
   Compiling regex-automata v0.3.8
   Compiling ring v0.16.20
   Compiling generic-array v0.14.7
   Compiling ryu v1.0.15
   Compiling crossbeam-utils v0.8.16
   Compiling hashbrown v0.12.3
   Compiling rand_core v0.5.1
   Compiling serde_derive v1.0.188
   Compiling thiserror-impl v1.0.48
   Compiling futures-macro v0.3.28
   Compiling tokio-macros v2.1.0
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling tokio v1.32.0
   Compiling lazy_static v1.4.0
   Compiling serde_json v1.0.105
   Compiling simd-adler32 v0.3.7
   Compiling vcpkg v0.2.15
   Compiling percent-encoding v2.3.0
   Compiling byteorder v1.4.3
   Compiling rand_chacha v0.2.2
   Compiling rand_pcg v0.2.1
   Compiling http v0.2.9
   Compiling untrusted v0.7.1
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.6.0
   Compiling rand v0.7.3
   Compiling tracing-attributes v0.1.26
   Compiling phf_shared v0.8.0
   Compiling tracing-core v0.1.31
   Compiling fastrand v2.0.0
   Compiling adler v1.0.2
   Compiling miniz_oxide v0.7.1
   Compiling tracing v0.1.37
   Compiling phf_generator v0.8.0
   Compiling unicode-normalization v0.1.22
   Compiling crypto-common v0.1.6
   Compiling rand_core v0.6.4
   Compiling time-core v0.1.1
   Compiling crc32fast v1.3.2
   Compiling unicode-bidi v0.3.13
   Compiling same-file v1.0.6
   Compiling walkdir v2.3.3
   Compiling time-macros v0.2.14
   Compiling tempfile v3.8.0
   Compiling libz-sys v1.1.12
   Compiling form_urlencoded v1.2.0
   Compiling num_threads v0.1.6
   Compiling subtle v2.5.0
   Compiling deranged v0.3.8
   Compiling semver v1.0.18
   Compiling wasm-bindgen-shared v0.2.87
   Compiling core-foundation-sys v0.8.4
   Compiling rand_chacha v0.3.1
   Compiling idna v0.4.0
   Compiling block-buffer v0.10.4
   Compiling bstr v1.6.2
   Compiling indexmap v1.9.3
   Compiling time v0.3.28
   Compiling hashbrown v0.14.0
   Compiling ucd-trie v0.1.6
   Compiling equivalent v1.0.1
   Compiling pest v2.7.3
   Compiling indexmap v2.0.0
   Compiling url v2.4.1
   Compiling digest v0.10.7
   Compiling rand v0.8.5
   Compiling phf_shared v0.10.0
   Compiling cpufeatures v0.2.9
   Compiling memoffset v0.9.0
   Compiling httparse v1.8.0
   Compiling ident_case v1.0.1
   Compiling strsim v0.10.0
   Compiling tower-service v0.3.2
   Compiling anyhow v1.0.75
   Compiling gix-trace v0.1.3
   Compiling darling_core v0.20.3
   Compiling phf_generator v0.10.0
   Compiling pest_meta v2.7.3
   Compiling flate2 v1.0.27
   Compiling phf_codegen v0.8.0
   Compiling faster-hex v0.8.0
   Compiling sct v0.7.0
   Compiling http-body v0.4.5
   Compiling crossbeam-epoch v0.9.15
   Compiling base64 v0.21.3
   Compiling camino v1.1.6
   Compiling either v1.9.0
   Compiling darling_macro v0.20.3
   Compiling gix-hash v0.12.0
   Compiling pest_generator v2.7.3
   Compiling core-foundation v0.9.3
   Compiling security-framework-sys v2.9.1
   Compiling tokio-util v0.7.8
   Compiling regex v1.9.5
   Compiling pin-project-internal v1.1.3
   Compiling socket2 v0.4.9
   Compiling matches v0.1.10
   Compiling httpdate v1.0.3
   Compiling utf-8 v0.7.6
   Compiling unicode-segmentation v1.10.1
   Compiling sha1_smol v1.0.0
   Compiling async-trait v0.1.73
   Compiling heck v0.3.3
   Compiling gix-features v0.33.0
   Compiling security-framework v2.9.2
   Compiling pin-project v1.1.3
   Compiling pest_derive v2.7.3
   Compiling darling v0.20.3
   Compiling phf_macros v0.8.0
   Compiling cargo-platform v0.1.3
   Compiling openssl-sys v0.9.92
   Compiling crossbeam-channel v0.5.8
   Compiling is-terminal v0.4.9
   Compiling unicase v2.7.0
   Compiling crunchy v0.2.2
   Compiling new_debug_unreachable v1.0.4
   Compiling try-lock v0.2.4
   Compiling fixedbitset v0.4.2
   Compiling rayon-core v1.11.0
   Compiling bumpalo v3.13.0
   Compiling rustls v0.21.7
   Compiling petgraph v0.6.4
   Compiling want v0.3.1
   Compiling wasm-bindgen-backend v0.2.87
   Compiling phf v0.8.0
   Compiling cargo_metadata v0.15.4
   Compiling crossbeam-deque v0.8.3
   Compiling walrus-macro v0.19.0
   Compiling h2 v0.3.21
   Compiling string_cache_codegen v0.5.2
   Compiling rustls-webpki v0.101.4
   Compiling zstd-sys v2.0.8+zstd.1.5.5
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling cfg-expr v0.12.0
   Compiling winnow v0.5.15
   Compiling leb128 v0.2.5
   Compiling rustc-hash v1.1.0
   Compiling precomputed-hash v0.1.1
   Compiling native-tls v0.2.11
   Compiling tiny-keccak v2.0.2
   Compiling id-arena v2.2.1
   Compiling smallbox v0.8.1
   Compiling heck v0.4.1
   Compiling mac v0.1.1
   Compiling wasmparser v0.77.1
   Compiling longest-increasing-subsequence v0.1.0
   Compiling static_assertions v1.1.0
   Compiling futf v0.1.5
   Compiling dioxus-core v0.4.2
   Compiling hyper v0.14.27
   Compiling walrus v0.19.0
   Compiling krates v0.12.6
   Compiling markup5ever v0.10.1
   Compiling wasm-bindgen-macro-support v0.2.87
   Compiling cssparser v0.27.2
   Compiling internment v0.7.1
   Compiling libssh2-sys v0.3.0
   Compiling doc-comment v0.3.3
   Compiling event-listener v2.5.3
   Compiling wasm-bindgen v0.2.87
   Compiling home v0.5.5
   Compiling mime v0.3.17
   Compiling dtoa v1.0.9
   Compiling dtoa-short v0.3.4
   Compiling gix-path v0.9.0
   Compiling dioxus-rsx v0.4.0
   Compiling wasm-bindgen-macro v0.2.87
   Compiling tendril v0.4.3
   Compiling string_cache v0.8.7
   Compiling gix-fs v0.5.0
   Compiling selectors v0.22.0
   Compiling gix-date v0.7.4
   Compiling concurrent-queue v2.2.0
   Compiling html5ever v0.25.2
   Compiling cssparser-macros v0.6.1
   Compiling btoi v0.4.3
   Compiling curl-sys v0.4.65+curl-8.2.1
   Compiling num-integer v0.1.45
   Compiling alloc-no-stdlib v2.0.4
   Compiling utf8parse v0.2.1
   Compiling zstd-safe v5.0.2+zstd.1.5.2
   Compiling nodrop v0.1.14
   Compiling itoa v0.4.8
   Compiling prettier-please v0.2.0
   Compiling safemem v0.3.3
   Compiling stable_deref_trait v1.2.0
   Compiling tower-layer v0.3.2
   Compiling convert_case v0.4.0
   Compiling servo_arc v0.1.1
   Compiling anstyle-parse v0.2.1
   Compiling derive_more v0.99.17
   Compiling alloc-stdlib v0.2.2
   Compiling gix-actor v0.25.0
   Compiling async-channel v1.9.0
   Compiling gix-tempfile v8.0.0
   Compiling rustc_version v0.4.0
   Compiling const-random-macro v0.1.15
   Compiling rayon v1.7.0
   Compiling kstring v2.0.0
   Compiling itertools v0.10.5
   Compiling rustls-pemfile v1.0.3
   Compiling sha1 v0.10.5
   Compiling gix-validate v0.8.0
   Compiling gix-utils v0.1.5
   Compiling fxhash v0.2.1
   Compiling fdeflate v0.3.0
   Compiling inout v0.1.3
   Compiling liquid-derive v0.26.4
   Compiling libgit2-sys v0.15.2+1.6.4
   Compiling backtrace v0.3.69
   Compiling nanorand v0.7.0
   Compiling spin v0.9.8
   Compiling filetime v0.2.22
   Compiling smartstring v1.0.1
   Compiling ahash v0.8.3
   Compiling num-rational v0.4.1
   Compiling fastrand v1.9.0
   Compiling weezl v0.1.7
   Compiling anstyle v1.0.2
   Compiling parking v2.1.0
   Compiling gimli v0.28.0
   Compiling colorchoice v1.0.0
   Compiling base64ct v1.6.0
   Compiling rustls v0.20.9
   Compiling portable-atomic v1.4.3
   Compiling unicode-width v0.1.10
   Compiling unicode-xid v0.2.4
   Compiling anstyle-query v1.0.0
   Compiling base64 v0.13.1
   Compiling anymap2 v0.13.0
   Compiling uuid v1.4.1
   Compiling rustc-demangle v0.1.23
   Compiling thin-slice v0.1.1
   Compiling match_cfg v0.1.0
   Compiling waker-fn v1.1.0
   Compiling failure_derive v0.1.8
   Compiling futures-lite v1.13.0
   Compiling hostname v0.3.1
   Compiling cfb v0.7.3
   Compiling liquid-core v0.26.4
   Compiling anstream v0.3.2
   Compiling addr2line v0.21.0
   Compiling synstructure v0.12.6
   Compiling console v0.15.7
   Compiling password-hash v0.4.2
   Compiling flume v0.10.14
   Compiling jpeg-decoder v0.3.0
   Compiling png v0.17.10
   Compiling cipher v0.4.4
   Compiling gix-lock v8.0.0
   Compiling gix-object v0.35.0
   Compiling js-sys v0.3.64
   Compiling const-random v0.1.15
   Compiling interprocess-docfix v1.2.2
   Compiling mime_guess v2.0.4
   Compiling brotli-decompressor v2.3.4
   Compiling tower v0.4.13
   Compiling async-lock v2.8.0
   Compiling tokio-rustls v0.24.1
   Compiling wasm-bindgen-wasm-conventions v0.2.87
   Compiling enum-as-inner v0.5.1
   Compiling serde_with_macros v3.3.0
   Compiling enumset_derive v0.8.1
   Compiling idna v0.2.3
   Compiling phf_macros v0.10.0
   Compiling sha-1 v0.10.1
   Compiling sha2 v0.10.7
   Compiling hmac v0.12.1
   Compiling treediff v4.0.2
   Compiling serde_spanned v0.6.3
   Compiling toml_datetime v0.6.3
   Compiling webpki v0.22.1
   Compiling rustls-webpki v0.100.2
   Compiling zune-inflate v0.2.54
   Compiling ordered-float v2.10.0
   Compiling nix v0.26.4
   Compiling memmap2 v0.7.1
   Compiling xattr v1.0.1
   Compiling atty v0.2.14
   Compiling time v0.1.45
   Compiling object v0.32.1
   Compiling cvt v0.1.2
   Compiling http-range-header v0.3.1
   Compiling ipnet v2.8.0
   Compiling atomic-waker v1.1.1
   Compiling lebe v0.5.2
   Compiling names v0.14.0
   Compiling color_quant v1.1.0
   Compiling async-task v4.4.0
   Compiling clap_lex v0.5.1
   Compiling paste v1.0.14
   Compiling quick-error v1.2.3
   Compiling bytemuck v1.13.1
   Compiling data-encoding v2.4.0
   Compiling minimal-lexical v0.2.1
   Compiling bit_field v0.10.2
   Compiling linked-hash-map v0.5.6
   Compiling glob v0.3.1
   Compiling is_ci v1.1.1
   Compiling rle-decode-fast v1.0.3
   Compiling curl v0.4.44
   Compiling half v2.2.1
   Compiling libflate_lz77 v1.2.0
   Compiling lru-cache v0.1.2
   Compiling exr v1.7.0
   Compiling supports-color v1.3.1
   Compiling nom v7.1.3
   Compiling trust-dns-proto v0.22.0
   Compiling qoi v0.4.1
   Compiling resolv-conf v0.7.0
   Compiling clap_builder v4.3.24
   Compiling blocking v1.3.1
   Compiling gif v0.12.0
   Compiling fs_at v0.1.9
   Compiling tar v0.4.40
   Compiling gix-ref v0.35.0
   Compiling serde-value v0.7.0
   Compiling webpki-roots v0.23.1
   Compiling toml_edit v0.19.14
   Compiling phf v0.10.1
   Compiling json-patch v1.0.0
   Compiling pbkdf2 v0.11.0
   Compiling enumset v1.1.2
   Compiling tungstenite v0.17.3
   Compiling serde_with v3.3.0
   Compiling brotli v3.3.4
   Compiling web-sys v0.3.64
   Compiling kuchiki v0.8.1
   Compiling tiff v0.9.0
   Compiling aes v0.8.3
   Compiling liquid-lib v0.26.4
   Compiling infer v0.12.0
   Compiling line-wrap v0.1.1
   Compiling tokio-native-tls v0.3.1
   Compiling gix-glob v0.11.0
   Compiling gix-config-value v0.13.0
   Compiling keyboard-types v0.6.2
   Compiling clap_derive v4.3.12
   Compiling globset v0.4.13
   Compiling serde_urlencoded v0.7.1
   Compiling euclid v0.22.9
   Compiling headers-core v0.2.0
   Compiling ctor v0.1.26
   Compiling rhai_codegen v1.5.0
   Compiling serde_repr v0.1.16
   Compiling gix-sec v0.9.0
   Compiling spinning v0.1.0
   Compiling dirs-sys-next v0.1.2
   Compiling thread_local v1.1.7
   Compiling path-dedot v3.1.0
   Compiling quick-xml v0.29.0
   Compiling unicode-bom v2.0.2
   Compiling shell-words v1.1.0
   Compiling termcolor v1.2.0
   Compiling intmap v0.7.1
   Compiling to_method v1.1.0
   Compiling humantime v2.1.0
   Compiling constant_time_eq v0.1.5
   Compiling adler32 v1.2.0
   Compiling number_prefix v0.4.0
   Compiling dunce v1.0.4
   Compiling zeroize v1.6.0
   Compiling normpath v1.1.1
   Compiling remove_dir_all v0.8.2
   Compiling dialoguer v0.10.4
   Compiling tauri-utils v1.4.0
   Compiling indicatif v0.17.6
   Compiling libflate v1.4.0
   Compiling env_logger v0.10.0
   Compiling plist v1.5.0
   Compiling gix-config v0.28.0
   Compiling rhai v1.15.1
   Compiling ignore v0.4.20
   Compiling path-absolutize v3.1.0
   Compiling dirs-next v2.0.0
   Compiling dioxus-html v0.4.0
   Compiling clap v4.3.24
   Compiling headers v0.3.9
   Compiling liquid v0.26.4
   Compiling hyper-tls v0.5.0
   Compiling failure v0.1.8
   Compiling async-compression v0.3.15
   Compiling image v0.24.7
   Compiling tokio-tungstenite v0.17.2
   Compiling toml v0.7.6
   Compiling tokio-rustls v0.23.4
   Compiling ureq v2.7.1
   Compiling trust-dns-resolver v0.22.0
   Compiling iri-string v0.4.1
   Compiling owo-colors v3.5.0
   Compiling tower-http v0.3.5
   Compiling wasm-bindgen-wasm-interpreter v0.2.87
   Compiling wasm-bindgen-threads-xform v0.2.87
   Compiling hyper-rustls v0.24.1
   Compiling dioxus-autofmt v0.4.0
   Compiling tauri-icns v0.1.0
   Compiling rustls-native-certs v0.6.3
   Compiling html_parser v0.7.0
   Compiling axum-core v0.2.9
   Compiling base64 v0.9.3
   Compiling wasm-bindgen-externref-xform v0.2.87
   Compiling wasm-bindgen-multi-value-xform v0.2.87
   Compiling colored v1.9.4
   Compiling handlebars v4.4.0
   Compiling sanitize-filename v0.5.0
   Compiling iana-time-zone v0.1.57
   Compiling toml v0.5.11
   Compiling futures-executor v0.3.28
   Compiling nix v0.27.1
   Compiling dirs-sys v0.3.7
   Compiling dirs v1.0.5
   Compiling fsevent-sys v4.1.0
   Compiling os_pipe v1.1.4
   Compiling encoding_rs v0.8.33
   Compiling webpki-roots v0.25.2
   Compiling siphasher v0.2.3
   Compiling is_executable v0.1.2
   Compiling arc-swap v1.6.0
   Compiling sync_wrapper v0.1.2
   Compiling convert_case v0.5.0
   Compiling hex v0.3.2
   Compiling pathdiff v0.2.1
   Compiling matchit v0.5.0
   Compiling hex v0.4.3
   Compiling dioxus-cli v0.4.0
   Compiling axum v0.5.17
   Compiling open v4.2.0
   Compiling rsx-rosetta v0.4.0
   Compiling axum-server v0.5.1
   Compiling reqwest v0.11.20
   Compiling notify v5.2.0
   Compiling ctrlc v3.4.1
   Compiling dirs v4.0.0
   Compiling cargo_toml v0.11.8
   Compiling futures v0.3.28
   Compiling chrono v0.4.28
   Compiling fern v0.6.2
   Compiling wasm-bindgen-cli-support v0.2.87
   Compiling hyper-rustls v0.23.2
   Compiling dioxus-check v0.4.0
   Compiling tower-http v0.2.5
   Compiling dioxus-hot-reload v0.4.0
   Compiling gitignore v1.0.8
   Compiling colored v2.0.4
   Compiling subprocess v0.2.9
   Compiling fs_extra v1.3.0
   Compiling bzip2 v0.4.4
   Compiling zip v0.5.13
   Compiling binary-install v0.0.2
   Compiling zstd v0.11.2+zstd.1.5.2
   Compiling zip v0.6.6
   Compiling tauri-bundler v1.3.0
   Compiling git2 v0.17.2
   Compiling cargo-generate v0.18.4
error[E0063]: missing field `desktop_template` in initializer of `tauri_bundler::DebianSettings`
   --> /Users/uriah/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-cli-0.4.0/src/config.rs:381:9
    |
381 |         tauri_bundler::DebianSettings {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `desktop_template`

error[E0063]: missing fields `custom_language_files` and `template` in initializer of `tauri_bundler::NsisSettings`
   --> /Users/uriah/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-cli-0.4.0/src/config.rs:517:9
    |
517 |         tauri_bundler::NsisSettings {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `custom_language_files` and `template`

For more information about this error, try `rustc --explain E0063`.
The following warnings were emitted during compilation:

warning: Could not find `.git/HEAD` from manifest dir!

error: could not compile `dioxus-cli` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `dioxus-cli v0.4.0`, intermediate artifacts can be found at `/var/folders/m0/lw8c2dfd4zb7zl_1b48k9y0r0000gn/T/cargo-installSOJBSG`
</code>
</details>

But its odd since installing it by this command works

```sh
cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli
```
 
but then again...  im not running the stable version

I tried installing again
```sh
cargo install dioxus-cli --locked --force
```

That work out as well.

but then again...

when i run dx serve using dx git version i got this

<details>
<summary> I got this error</summary>
<code>
[INFO] 🚅 Running build command...
Error: 🚫 Serving project failed: error: Your target operating system is not supported by interprocess – check if yours is in the list of supported systems, and if not, please open an issue on the GitHub repository if you think that it should be included
  --> /Users/uriah/.cargo/registry/src/index.crates.io-6f17d22bba15001f/interprocess-docfix-1.2.2/src/lib.rs:82:1
   |
82 | compile_error!("Your target operating system is not supported by interprocess – check if yours is in the list of supported systems, and if not, please open an issue on the GitHub repository if you think that it should be included...
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Broken pipe (os error 32)
error: could not compile `interprocess-docfix` (lib) due to 15 previous errors
</code>
</details>

when i run dx serve using dx locked version i got this

<details>
<summary>Errors</summary>
<code>
[INFO] 🚅 Running build command...
   Compiling proc-macro2 v1.0.66
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling futures-task v0.3.28
   Compiling futures-core v0.3.28
   Compiling serde v1.0.188
   Compiling log v0.4.20
   Compiling futures-channel v0.3.28
   Compiling futures-util v0.3.28
   Compiling wasm-bindgen-shared v0.2.87
   Compiling crossbeam-utils v0.8.16
   Compiling pin-project-lite v0.2.13
   Compiling libc v0.2.147
   Compiling wasm-bindgen v0.2.87
   Compiling slab v0.4.9
   Compiling num-traits v0.2.16
   Compiling ident_case v1.0.1
   Compiling instant v0.1.12
   Compiling pin-utils v0.1.0
   Compiling thiserror v1.0.48
   Compiling quote v1.0.33
   Compiling semver v1.0.18
   Compiling syn v2.0.31
   Compiling event-listener v2.5.3
   Compiling concurrent-queue v2.2.0
   Compiling serde_json v1.0.105
   Compiling unicode-ident v1.0.11
   Compiling smallbox v0.8.1
   Compiling rustc-hash v1.1.0
   Compiling bumpalo v3.13.0
   Compiling longest-increasing-subsequence v0.1.0
   Compiling itoa v1.0.9
   Compiling bitflags v1.3.2
   Compiling bytes v1.4.0
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.6.0
   Compiling async-channel v1.9.0
   Compiling lock_api v0.4.10
   Compiling async-trait v0.1.73
   Compiling ryu v1.0.15
   Compiling unicode-normalization v0.1.22
   Compiling rustc_version v0.4.0
   Compiling cc v1.0.83
   Compiling ordered-float v2.10.0
   Compiling num_cpus v1.16.0
   Compiling fastrand v1.9.0
   Compiling parking v2.1.0
   Compiling percent-encoding v2.3.0
   Compiling unicode-bidi v0.3.13
   Compiling unicode-segmentation v1.10.1
   Compiling futures-io v0.3.28
   Compiling fnv v1.0.7
   Compiling scopeguard v1.2.0
   Compiling waker-fn v1.1.0
   Compiling memchr v2.6.3
   Compiling form_urlencoded v1.2.0
   Compiling idna v0.4.0
   Compiling interprocess-docfix v1.2.2
   Compiling futures-lite v1.13.0
   Compiling async-lock v2.8.0
   Compiling once_cell v1.18.0
   Compiling wasm-bindgen-backend v0.2.87
   Compiling darling_core v0.20.3
   Compiling async-task v4.4.0
   Compiling tao v0.19.1
   Compiling atomic-waker v1.1.1
   Compiling url v2.4.1
   Compiling blocking v1.3.1
   Compiling spinning v0.1.0
   Compiling dioxus-core v0.4.2
   Compiling crossbeam-channel v0.5.8
   Compiling wasm-bindgen-macro-support v0.2.87
   Compiling to_method v1.1.0
   Compiling raw-window-handle v0.5.2
   Compiling wry v0.28.3
   Compiling intmap v0.7.1
   Compiling lazy_static v1.4.0
   Compiling uuid v1.4.1
   Compiling byteorder v1.4.3
   Compiling dioxus-rsx v0.4.0
   Compiling cfb v0.7.3
   Compiling http v0.2.9
   Compiling dioxus-debug-cell v0.1.1
   Compiling dioxus-interpreter-js v0.4.0
   Compiling infer v0.11.0
   Compiling urlencoding v2.1.3
   Compiling dunce v1.0.4
   Compiling serde_derive v1.0.188
   Compiling wasm-bindgen-macro v0.2.87
   Compiling thiserror-impl v1.0.48
   Compiling darling_macro v0.20.3
   Compiling tokio-macros v2.1.0
   Compiling serde_repr v0.1.16
   Compiling darling v0.20.3
   Compiling enumset_derive v0.8.1
   Compiling js-sys v0.3.64
   Compiling dioxus-core-macro v0.4.0
   Compiling tokio v1.32.0
Error: 🚫 Serving project failed: error: Only features sync,macros,io-util,rt,time are supported on wasm.cro, enumset_derive, js-sys, serde_derive
   --> /Users/uriah/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/lib.rs:471:1
    |
471 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Broken pipe (os error 32)
warning: build failed, waiting for other jobs to finish...
</code>
</details>

The command i can run:

```sh
dx serve --hot-reload --platform desktop
dx bundle
```

this works, but Another Issue also occurs to me

if i run 
```sh
cargo watch  -x 'run --'
npx tailwindcss -i ./input.css -o ./public/tailwind.css --watch
```

tailwind works out of the box
e.g. this would render a red text on cargo run but not on dx serve --hot-reload --platform desktop
 
```rust
h1 {
                class: "font-serif italic text-red-900",
                "🌗 Dioxus 🚀"
}
```

Note: I already added wasm

```sh
rustup target add wasm32-unknown-unknown
```

see my rustup details

```
rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/uriah/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
stable-x86_64-unknown-linux-gnu
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-unknown-linux-gnu
wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.71.0 (8ede3aae2 2023-07-12)
```

**Comment by ealmloff** [comment] 2023-09-04 13:45
The installation error is a duplicate of https://github.com/DioxusLabs/dioxus/issues/1413. The git version has been fixed, and the docs now instruct users to install the cli with `--locked`.

The first error is because you are trying to build a desktop application with the wasm target which is not supported. `desktop` tells the CLI to not target wasm which fixes the issue.

> this works, but Another Issue also occurs to me
> 
> if i run
> 
> cargo watch  -x 'run --'
> npx tailwindcss -i ./input.css -o ./public/tailwind.css --watch
> tailwind works out of the box
> e.g. this would render a red text on cargo run but not on dx serve --hot-reload --platform desktop
> 
> h1 {
>                 class: "font-serif italic text-red-900",
>                 "🌗 Dioxus 🚀"
> }

Cargo run and `dx serve` run the binary from different locations which makes the path `public/tailwind.css` not work. The CLI copies all `public/*` files into the same directory as the application so you can just use `tailwind.css` instead of `public/tailwind.css`. https://github.com/DioxusLabs/dioxus/pull/1369 should make assets a bit more consistant

**Closed** 2023-09-09 21:09 UTC
Labels: bug, cli
