### ISSUE TITLE
Dioxus CLI prebuilt binaries

### ISSUE THREAD

**Issue by arqalite** [DioxusLabs/dioxus#1380] opened 2023-08-20 10:40 UTC
## Specific Demand

While migrating from 0.3 to 0.4, I noticed the CLI takes much longer to compile, up to 15 minutes on Vercel and GitHub Actions. Even on my machine it takes 7-8 minutes.

Would it be possible to supply prebuilt binaries, for amd64 Windows and Linux at least?
It will help users that integrate with CI/CD platforms to reduce the overall deployment time instead of having to compile the CLI from source every time (caching can help, but it depends on the platform).

## Implement Suggestion

I believe a GitHub Action could do this pretty easily, but it might incur costs depending on what plan the project is on.

**Comment by Demonthos** [comment] 2023-08-20 15:05
There will be prebuilt binaries the next time a new release is published. This was added in https://github.com/DioxusLabs/dioxus/issues/1331

Closing this as a duplicate of https://github.com/DioxusLabs/dioxus/issues/1331

**Closed by Demonthos** 2023-08-20 15:05 UTC
