### ISSUE TITLE
unresolved import `crate::sys::IoSourceState`build, while compling `mio`

### ISSUE THREAD

**Issue by qtisan** [DioxusLabs/dioxus#1330] opened 2023-08-09 15:09 UTC
**Problem**

Got error when running `dx serve --hot-reload`.

```
[INFO] 🚅 Running build command...
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.18.0
   Compiling log v0.4.19
   Compiling bumpalo v3.13.0
   Compiling wasm-bindgen-shared v0.2.87
   Compiling autocfg v1.1.0
   Compiling wasm-bindgen v0.2.87
   Compiling version_check v0.9.4
   Compiling memchr v2.5.0
   Compiling serde_derive v1.0.183
   Compiling itoa v1.0.9
   Compiling futures-core v0.3.28
   Compiling serde v1.0.183
   Compiling pin-project-lite v0.2.11
   Compiling slab v0.4.8
   Compiling bytes v1.4.0
   Compiling quote v1.0.32
   Compiling syn v2.0.28
   Compiling futures-sink v0.3.28
   Compiling futures-io v0.3.28
   Compiling futures-channel v0.3.28
   Compiling futures-task v0.3.28
   Compiling typenum v1.16.0
   Compiling wasm-bindgen-backend v0.2.87
   Compiling wasm-bindgen-macro-support v0.2.87
   Compiling generic-array v0.14.7
   Compiling libc v0.2.147
   Compiling wasm-bindgen-macro v0.2.87
   Compiling thiserror v1.0.44
   Compiling futures-util v0.3.28
   Compiling futures-macro v0.3.28
   Compiling thiserror-impl v1.0.44
   Compiling pin-utils v0.1.0
   Compiling fnv v1.0.7
   Compiling http v0.2.9
   Compiling serde_json v1.0.104
   Compiling jobserver v0.1.26
   Compiling ryu v1.0.15
   Compiling cc v1.0.82
   Compiling tokio v1.29.1
   Compiling num_cpus v1.16.0
   Compiling tokio-macros v2.1.0
   Compiling mio v0.8.8
Error: 🚫 Serving project failed: error[E0432]: unresolved import `crate::sys::IoSourceState`, thiserror-impl, mi...
  --> /root/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/mio-0.8.8/src/io_source.rs:12:5
   |
12 | use crate::sys::IoSourceState;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`


error: Broken pipe (os error 32)
warning: build failed, waiting for other jobs to finish...
Building [===>                      ] 70/431: tokio-
error: could not compile `mio` (lib) due to 45 previous errors
```

**Steps To Reproduce**

- New dev container in Docker, and open it in VSCode
- Follow the instructions from the Official website docs
- Use the default template by `dx create`, with `router`, `Salvo`, `tailwindcss`, `Fullstack`
- `dx serve --hot-reload`

**Expected behavior**

Runs fine.

**Screenshots**

Cargo.toml
```toml
[package]
name = "moerae-app"
version = "0.1.0"
authors = ["SiloQIAN <qtisan@hotmail.com>"]
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-liveview = { version = "0.4", features = ["salvo"] }
salvo = { version = "0.37.9", features = ["ws"] }
dioxus-fullstack = { version = "0.4", features = ["router"] }
dioxus = { version = "0.4" }
serde = { version = "1.0.159", features = ["derive"] }
dioxus-router = { version = "0.4" }
getrandom = { version = "0.2", features = ["js"] }

log = "0.4.6"
dioxus-logger = "0.4.1"

[features]
default = []
ssr = ["dioxus-fullstack/salvo"]
web = ["dioxus-router/web", "dioxus-fullstack/web"]

# Debug
# log = "0.4.19"
# dioxus-logger = "0.4.1"
```

**Environment:**
 - Dioxus version: 0.4
 - Rust version: 1.71.1
 - OS info: Docker Devcontainer, debian 11.4, MacOS hosted
 - App platform: Fullstack, web

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

I found some error most likely as in the `mio` repo: https://github.com/tokio-rs/mio/issues/1681

**Maybe is it somewhere uses mio at the frontend?**

**Comment by DoctorRyner** [comment] 2023-08-09 18:16
+++

I have the same issue

**Comment by Demonthos** [comment] 2023-08-09 18:22
The template was updated recently. Running with the new template there are some errors with the log crate (that will be resolved in ). After fixing those, I get this as my `cargo.toml`:

```toml
[package]
name = "testing-fullstack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-fullstack = { version = "0.4", features = ["router"] }
dioxus = { version = "0.4" }
serde = { version = "1.0.159", features = ["derive"] }
dioxus-router = { version = "0.4" }
# Debug
log = "0.4.19"
dioxus-logger = "0.4.1"

[features]
default = []
ssr = ["dioxus-fullstack/salvo"]
web = ["dioxus-router/web", "dioxus-fullstack/web"]
```

From there you can run this to start the server:

```sh
dx build --features web --release
cargo run --features ssr --release
```

**Comment by qtisan** [comment] 2023-08-10 01:57
I noticed this `template` problem, and just changed manually.
`dx build --features web --release` that still get the same error:  unresolved import `crate::sys::IoSourceState`.

Could you tell me how to trace into the source code to find out where it caused? @Demonthos 

> The template was updated recently. Running with the new template there are some errors with the log crate (that will be resolved in [DioxusLabs/dioxus-template#6](https://github.com/DioxusLabs/dioxus-template/pull/6)). After fixing those, I get this as my `cargo.toml`:
> 
> ```toml
> [package]
> name = "testing-fullstack"
> version = "0.1.0"
> edition = "2021"
> 
> # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
> 
> [dependencies]
> dioxus-fullstack = { version = "0.4", features = ["router"] }
> dioxus = { version = "0.4" }
> serde = { version = "1.0.159", features = ["derive"] }
> dioxus-router = { version = "0.4" }
> # Debug
> log = "0.4.19"
> dioxus-logger = "0.4.1"
> 
> [features]
> default = []
> ssr = ["dioxus-fullstack/salvo"]
> web = ["dioxus-router/web", "dioxus-fullstack/web"]
> ```
> 
> From there you can run this to start the server:
> 
> ```shell
> dx build --features web --release
> cargo run --features ssr --release
> ```

**Comment by qtisan** [comment] 2023-08-10 02:34
I changed the `default_platform` to `ssr` in Dioxus.toml, then got:

```
Error: Failed to load Dioxus config because: Dioxus.toml unknown variant `ssr`, expected `web` or `desktop` for key `application.default_platform` at line 39 column 1
```

not support?

```
# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "ssr"

```

**Comment by Demonthos** [comment] 2023-08-10 16:47
(Sorry I didn't mean to edit your message)

Yes that isn't supported yet. See https://github.com/DioxusLabs/dioxus/issues/1334

**Comment by Demonthos** [comment] 2023-08-10 16:48
> I noticed this `template` problem, and just changed manually. `dx build --features web --release` that still get the same error: unresolved import `crate::sys::IoSourceState`.
> 
> Could you tell me how to trace into the source code to find out where it caused? @Demonthos
> 
> > The template was updated recently. Running with the new template there are some errors with the log crate (that will be resolved in [DioxusLabs/dioxus-template#6](https://github.com/DioxusLabs/dioxus-template/pull/6)). After fixing those, I get this as my `cargo.toml`:
> > ```toml
> > [package]
> > name = "testing-fullstack"
> > version = "0.1.0"
> > edition = "2021"
> > 
> > # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
> > 
> > [dependencies]
> > dioxus-fullstack = { version = "0.4", features = ["router"] }
> > dioxus = { version = "0.4" }
> > serde = { version = "1.0.159", features = ["derive"] }
> > dioxus-router = { version = "0.4" }
> > # Debug
> > log = "0.4.19"
> > dioxus-logger = "0.4.1"
> > 
> > [features]
> > default = []
> > ssr = ["dioxus-fullstack/salvo"]
> > web = ["dioxus-router/web", "dioxus-fullstack/web"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From there you can run this to start the server:
> > ```shell
> > dx build --features web --release
> > cargo run --features ssr --release
> > ```

The template is pulled from [this repo](https://github.com/DioxusLabs/dioxus-template). The log issue will be fixed by https://github.com/DioxusLabs/dioxus-template/pull/6

**Comment by Demonthos** [comment] 2023-08-21 14:51
> I have exactly the same error while `dx serve --hot-reload`, `cargo build` works smoothly:
> 
> ```
>    Compiling mio v0.8.8
> Error: 🚫 Serving project failed: error[E0432]: unresolved import `crate::sys::IoSourceState`
>   --> /home/tomek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.8/src/io_source.rs:12:5
>    |
> 12 | use crate::sys::IoSourceState;
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`
> ```

@TomaszWaszczyk 

That error is likely caused by tokio somewhere in your `cargo tree`. If you run `cargo tree` you can find where the tokio crate is being pulled in.

If you are using the template, some PRs have not been merged yet that should fix this. Your `cargo.toml` should look like:
```rust
[package]
name = "testing-fullstack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-fullstack = { version = "0.4", features = ["router"] }
dioxus = { version = "0.4" }
serde = { version = "1.0.159", features = ["derive"] }
dioxus-router = { version = "0.4" }
# Debug
log = "0.4.19"
dioxus-logger = "0.4.1"

[features]
default = []
ssr = ["dioxus-fullstack/salvo"]
web = ["dioxus-router/web", "dioxus-fullstack/web"]
```

Notice the `ssr` and `web` features. `dx serve --hot-reload`, and `cargo build` will do nothing. You need to set the `ssr` feature for the server and the `web` feature for the web.

```sh
dx build --features web --release
cargo run --features ssr --release
```

**Comment by TomaszWaszczyk** [comment] 2023-08-21 17:24
`dx build --features web --release` work, but while `cargo run --features ssr --release` I got:

```
tomek@rhei-box:~/.../wasm-dex-ui$ cargo run --features web --release
    Finished release [optimized] target(s) in 0.35s
     Running `target/release/wasm-dex-ui`
[INFO] wasm_dex_ui - Starting WebAssembly Decentralized Exchange
panicked at /home/tomek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5701:1:
cannot call wasm-bindgen imported functions on non-wasm targets
```

Was trying also with target, like: `cargo run --features ssr --release --target wasm32-unknown-unknown`, but got errors.

**Comment by Demonthos** [comment] 2023-08-21 18:53
> `dx build --features web --release` work, but while `cargo run --features ssr --release` I got:
> 
> ```
> tomek@rhei-box:~/.../wasm-dex-ui$ cargo run --features web --release
>     Finished release [optimized] target(s) in 0.35s
>      Running `target/release/wasm-dex-ui`
> [INFO] wasm_dex_ui - Starting WebAssembly Decentralized Exchange
> panicked at /home/tomek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5701:1:
> cannot call wasm-bindgen imported functions on non-wasm targets
> ```
> 
> Was trying also with target, like: `cargo run --features ssr --release --target wasm32-unknown-unknown`, but got errors.


You cannot use web-sys in any code that will run on the server. If you have some code that uses web-sys, you need to put it behind a `#[cfg(feature = "web")]` flag or inside an effect, event, or async block

**Comment by TomaszWaszczyk** [comment] 2023-08-21 22:16
@Demonthos  I do not fully understand `web-sys` dependency, but will read and thanks for the help.

**Closed** 2023-09-06 17:54 UTC
Labels: bug, cli, fullstack

**Comment by meri-leeworthy** [comment] 2023-10-10 11:34
I'm having the same issue if I run `dx build --features web --release` (as well as `dx serve`)

```
Error: 🚫 Building project failed: error[E0432]: unresolved import `crate::sys::IoSourceState`
  --> /Users/merileeworthy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.8/src/io_source.rs:12:5
   |
12 | use crate::sys::IoSourceState;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`
```

I also tried this one `argo run --features ssr --release --target wasm32-unknown-unknown` and got heeeaaps of errors about mio can't find xyz in sys

**Comment by ealmloff** [comment] 2023-10-10 14:05
> I'm having the same issue if I run `dx build --features web --release` (as well as `dx serve`)
> 
> ```
> Error: 🚫 Building project failed: error[E0432]: unresolved import `crate::sys::IoSourceState`
>   --> /Users/merileeworthy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.8/src/io_source.rs:12:5
>    |
> 12 | use crate::sys::IoSourceState;
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`
> ```
> 
> I also tried this one `cargo run --features ssr --release --target wasm32-unknown-unknown` and got heeeaaps of errors about mio can't find xyz in sys

What does your `cargo tree` look like? This is generally caused by tokio somewhere in your dependency tree which is not compatible with wasm

**Comment by meri-leeworthy** [comment] 2023-10-12 01:46
oh, that makes sense. I didn't realise you can't use tokio with wasm 😅 thank you!
