### ISSUE TITLE
3D

### ISSUE THREAD

**Issue by WREQI** [DioxusLabs/dioxus#1113] opened 2023-06-21 13:47 UTC
We want to use Trust to develop high-performance apps that support 3D and AR, such as Apple's Android app. Can this be achieved?

**Comment by Demonthos** [comment] 2023-06-21 14:51
Currently, Dioxus does not support any 3D renderers, but we do expose an API to allow you to create a [custom renderer](https://dioxuslabs.com/docs/nightly/guide/en/custom_renderer/index.html).

Closing this as a duplicate of https://github.com/DioxusLabs/dioxus/issues/265

**Closed by Demonthos** 2023-06-21 14:51 UTC
