### ISSUE TITLE
After adding the configuration, all routes are inaccessible

### ISSUE THREAD

**Issue by ys2rice2yangsong** [DioxusLabs/dioxus#1468] opened 2023-09-18 00:42 UTC
#![allow(non_snake_case)]
use dioxus::prelude::*;
use dioxus_router::prelude::*;
fn main() {
    dioxus_web::launch(App);
}

fn App(cx: Scope) -> Element {
    render! (
        Router::<Route>{}
    )
}

#[derive(Routable, Clone)]
enum Route {
    #[route("/login")]
    Login {},
    #[nest("/main")]
        #[layout(MainMaster)]
            #[route("/")]
            MainHome {},
        #[end_layout]
    #[end_nest]
    #[route("/:..route")]
    PageNotFound {
        route: Vec<String>
    }
}

fn Login(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "登录页面"
        }
    })
}

fn MainMaster(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "后台主页"
        }
        Outlet::<Route> {}
    })
}

#[inline_props]
fn PageNotFound(cx: Scope, route: Vec<String>) ->Element {
    cx.render(rsx! {
        div {
            "没有这个页面"
        }
    })
}

fn MainHome (cx: Scope) -> Element {
    render! {
        div {
            "这是后台主页面"
        }
    }
}

**Comment by ys2rice2yangsong** [comment] 2023-09-18 00:43
When there is no configuration, everything is normal, but when I add the following configuration, the page refresh error occurs

configure：


[application]

# App (Project) Name
name = "Tailwind CSS + Dioxus"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "dioxus | ⛺"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# uncomment line below if using Router
# index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["app.css"]

# Javascript code file
script = []

[web.resource.dev]

# serve: [dev-server] only

# CSS style file
style = []

# Javascript code file
script = []

**Comment by ys2rice2yangsong** [comment] 2023-09-18 00:50
A directory structure that can be accessed normally without configuration, and all routes can be accessed or refreshed. After adding a route, all routes cannot be accessed

![image](https://github.com/DioxusLabs/dioxus/assets/57334741/f5cb8cb4-62fe-4f6c-afe5-9b949ff240a8)
However, when I added the configuration, all the routes were inaccessible
![image](https://github.com/DioxusLabs/dioxus/assets/57334741/4af41b4c-d290-447c-890d-6581763f30cb)
![image](https://github.com/DioxusLabs/dioxus/assets/57334741/2843e8d2-967a-4bd6-9732-dffa437a7567)

**Comment by ys2rice2yangsong** [comment] 2023-09-18 00:50
![image](https://github.com/DioxusLabs/dioxus/assets/57334741/584bbbd9-d809-414b-8845-9c0a546ffb8e)
![image](https://github.com/DioxusLabs/dioxus/assets/57334741/6147ffe5-d423-493d-8ab0-65b9579973c8)

**Comment by ys2rice2yangsong** [comment] 2023-09-18 00:53
my  taiwindcss：
![image](https://github.com/DioxusLabs/dioxus/assets/57334741/66cc8214-9ad1-41ab-aca8-c831ebee526e)
tailwind.config.js:
module.exports = {
  purge: [
      '../src/**/*.rs'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      "tailwindCSS.experimental.classRegex": ["class: \"(.*)\""],
      "tailwindCSS.includeLanguages": {
          "rust": "html"
      },

    },
  },
  variants: {
    extend: {

    },
  },
  plugins: ["daisyui"],
}

postcss.config.js:
module.exports = {
    plugins: {
        tailwindcss: { config: './tailwind.config.js' },
        autoprefixer: {},
        'postcss-nested': {},
    }
}

main.pcss:
@tailwind base;

@tailwind components;

@tailwind utilities;

**Comment by ys2rice2yangsong** [comment] 2023-09-18 00:54
package.json:
{
  "name": "styles",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "NODE_ENV=production node_modules/.bin/postcss main.pcss -o ../public/app.css --watch"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "autoprefixer": "^10.4.15",
    "postcss": "^8.4.29",
    "postcss-cli": "^10.1.0",
    "tailwindcss": "^3.3.3"
  },
  "devDependencies": {
    "daisyui": "^3.7.3"
  }
}

**Comment by ealmloff** [comment] 2023-09-18 00:55
This is a duplicate of #1457. If you think an issue was closed too early, you can continue to comment on that issue to further explain why it is still a problem, and I would be happy to reopen it 🙂. Opening multiple issues for the same bug makes it difficult to keep track of the conversation.

(I edited your comment to format the code. Github displays the code with highlighting if you surround your code blocks like this:
\```toml
\**your code\**
\```
Otherwise your code gets formatted like text)

This part of the code needs to be uncommented because you are using the router:
```toml
# uncomment line below if using Router
# index_on_404 = true
```

It is confusing that this behavior changes when you add the default `diouxs.toml` file. That issue is discussed more in https://github.com/DioxusLabs/dioxus/issues/1291 along with the linked PR

**Comment by ys2rice2yangsong** [comment] 2023-09-18 05:24
I know, I mentioned a similar bug before, but this is a new project I have built and tested the bug mentioned earlier, and it has indeed been resolved. When I added tailwindcss according to the official document, the routing issue was the same as the bug I mentioned earlier, so I submitted another bug. Can you follow my steps to conduct a test? I have written all my steps clearly, and the reason for submitting two identical bugs is because the system prompts me that similar bugs have been submitted before and have been resolved.

**Comment by ys2rice2yangsong** [comment] 2023-09-18 05:28
i'm sorry.  You guys are working hard，thanks!!!

**Comment by ealmloff** [comment] 2023-09-18 13:15
> i'm sorry. You guys are working hard，thanks!!!

Did adding `index_on_404 = true` fix the issue?

**Closed** 2023-09-25 17:17 UTC
