### ISSUE TITLE
Access to raw web_sys::Event

### ISSUE THREAD

**Issue by theduke** [DioxusLabs/dioxus#793] opened 2023-01-22 11:00 UTC
Is there a way to get access to a raw web_sys::Event?

My concrete need is that I need to work with files in the browser, and the API provided by `FileEngine` is way too limited.

**Comment by jkelleyrtp** [comment] 2023-01-23 19:41
Not yet, but I'm working on a change that will add this to be released in the next bump of Dioxus.

**Comment by gbj** [comment] 2023-02-20 16:55
Duplicate of #93 if it’s helpful to know — always feels good to close two issues at once!

**Comment by ealmloff** [comment] 2024-01-09 22:15
done in https://github.com/DioxusLabs/dioxus/pull/1402

**Closed by ealmloff** 2024-01-09 22:15 UTC
Labels: enhancement, web
