### ISSUE TITLE
Using a `Future` stops `on*` events

### ISSUE THREAD

**Issue by terhechte** [DioxusLabs/dioxus#800] opened 2023-01-27 13:11 UTC
**Using a future causes onmousedown, onmouseleave, etc events to not trigger anymore**

I have this code (I couldn't make it much shorter for the example) which creates a draggable sidebar.

``` rs
use dioxus::prelude::*;
use dioxus_web::launch;

// mod sidebar;

fn main() {
    launch(App);
}

fn App(cx: Scope) -> Element {
    // Uncomment the future and mouse events stop working
    // let fut = use_future(cx, (), |_| async move {});
    cx.render(rsx! {
        SidebarContentComponent {
            sidebar: cx.render(rsx!(h3 {
                "Sidebar"
            })),
            content: cx.render(rsx!(h3 {
                "Content"
            }))
        }
    })
}

#[inline_props]
pub fn SidebarContentComponent<'a>(
    cx: Scope<'a>,
    sidebar: Element<'a>,
    content: Element<'a>,
) -> Element<'a> {
    let style_html = format!("<style>{STYLE}</style>");

    let size: &UseState<Option<f64>> = use_state(&cx, || Some(300.));
    let is_resizing = use_state(cx, || false);
    cx.render(rsx!(div { class: "sb-main",
        onmouseup: move |_| {
            if *is_resizing.current() {
                is_resizing.set(false);
            }
        },
        onmousemove: move |event| {
            if *is_resizing.current() == true {
                let value = event.data.page_coordinates().x - 8.;
                size.set(Some(value))
            }
        },
        div {
            dangerous_inner_html: "{style_html}"
        }
       SidebarComponent {
        size: size.clone(),
        is_resizing: is_resizing.clone(),
        sidebar
       }
       ResizeComponent {
        size: size.clone(),
        is_resizing: is_resizing.clone()
       }
       ContentComponent {
        is_resizing: is_resizing.clone()
        content
       }
    }))
}

#[inline_props]
fn SidebarComponent<'a>(
    cx: Scope<'a>,
    size: UseState<Option<f64>>,
    is_resizing: UseState<bool>,
    children: Element<'a>,
) -> Element<'a> {
    let style = if let Some(s) = *size.current() {
        format!("width: {s}px;")
    } else {
        "".to_string()
    };
    let class = is_resizing.then(|| "sb-is-resizing").unwrap_or_default();
    cx.render(rsx! {
        div {
            class: "sb-sidebar {class}",
            style: "{style}",
            children
        }
    })
}

#[inline_props]
fn ResizeComponent(cx: Scope, size: UseState<Option<f64>>, is_resizing: UseState<bool>) -> Element {
    let class = is_resizing.then(|| "sb-is-resizing").unwrap_or_default();
    cx.render(rsx!(div {
        class: "sb-resize {class}",
        onmousedown: move |_event| {
            is_resizing.set(true);
        },
        onmouseup: move |_event| { is_resizing.set(false) },
        onmouseout: move |event| {
            if *is_resizing.current() == true {
                let value = event.data.page_coordinates().x - 8.;
                size.set(Some(value))
            }
        }
    }))
}

#[inline_props]
fn ContentComponent<'a>(
    cx: Scope<'a>,
    is_resizing: UseState<bool>,
    children: Element<'a>,
) -> Element<'a> {
    let class = is_resizing.then(|| "sb-is-resizing").unwrap_or_default();
    cx.render(rsx! {
        div {
            class: "{class}",
            children
        }
    })
}

const STYLE: &str = r#"
    .sb-main {
        width: 100%;
        height: 100vh;
        display: flex;
        user-select: none;
    }
    .sb-sidebar {
        box-sizing: border-box;
        flex-shrink: 0;
        height: 100vh;
        width: 300px;
        background-color: #eee;
    }
    .sb-resize {
        width: 10px;
        flex: 0 0 auto;
        cursor: ew-resize;
        padding: 0;
        user-select: none;
        -webkit-user-select: none;
        background-color: #555;
    }
    .sb-content {
        box-sizing: border-box;
        height: 100%;
    }
    .sb-is-resizing {
        user-select: none;
        -webkit-user-select: none;
        pointer-events: none;
    }
    "#;

```

It took me a while to figure this out, but once a future is being run, the mouse events stop working and the resize doesn't resize anymore. I did check with debug output using `console.log` and the problem is not related to the `UseState<bool>` or the `UseState<Option<f64>>` but really that the `onmouseover` (etc) events are not triggered anymore.

Commenting the future back in and the problem disappears.
Interestingly, in a simpler non-nested example like:

``` rs
let fut = use_future(cx, async move {});
cx.render(rsx!(div {
  onmousemove: move |_| { print(..) }
  h3 { "Hello" }
}))
```

e.g. where the move events are not in nested containers, the problem doesn't appear.

The same thing happens when using `use_coroutine` instead of `use_future`.

I'd love to help debug this but I have no idea where and how to look. The problem seems to happen on Desktop and Web

**Environment:**
 - Dioxus version: master
 - OS info: macOS Ventura

**Comment by Demonthos** [comment] 2023-01-28 21:01
Futures are run on the main thread. The above future deadlocks the main rendering thread which can cause issues.

For blocking code, try using a [tokio task](https://dioxuslabs.com/nightly/guide/en/async/spawn.html#spawning-tokio-tasks) instead or use yield now from future utils:

```rust
use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch(App);
}

fn App(cx: Scope) -> Element {
    use_coroutine(cx, |_: UnboundedReceiver<()>| async {
        tokio::spawn(async {
            loop {
                println!("This is blocking")
            }
        })
        .await
        .unwrap()
    });

    render! {
        input {

        }
    }
}
```

There have been a few issues opened now relating to this. We should probably update the use_future, use_coroutine, etc. to include a note to use tokio tasks for blocking tasks

**Comment by terhechte** [comment] 2023-01-29 14:59
How does this future cause a deadlock? It literally does nothing:

``` rs
let fut = use_future(cx, (), |_| async move {});
```

However, the information that Futures run on the main thread is important. I'm using them for expensive background operations that shouldn't block the UI. So this change should then not block the UI, right (the `mouse` events still don't appear though):

``` rs
let cloned = sender_collection.clone();
    let coroutine = use_coroutine(
        cx,
        |mut rx: UnboundedReceiver<BoxFuture<'_, Action>>| async move {
            let value = tokio::task::spawn(async move {
                if let Some(task) = rx.next().await {
                    let output = task.await;
                    Some(output)
                } else {
                    None
                }
            })
            .await;
            if let Ok(n) = value {
                cloned.set(n);
            }
        },
    );

    if let Some(action) = sender_collection.get() {
       //  ... process output
   }
```

**Comment by Demonthos** [comment] 2023-01-29 15:11
> How does this future cause a deadlock? It literally does nothing:
> 
> ```rust
> let fut = use_future(cx, (), |_| async move {});
> ```

Sorry, I misread this part of the code. I thought there was a loop {}. This is definitely a bug then.

It seems to be an issue with quickly resolving futures. If you add a tokio::time::sleep in the future this issue is fixed. This could be a regression related to https://github.com/DioxusLabs/dioxus/issues/306

```rust
let fut = use_future(cx, (), |_| async move {
    // Usually fails
    // tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    // Usually works
    // tokio::time::sleep(std::time::Duration::from_millis(10000)).await;
});
```

**Comment by terhechte** [comment] 2023-01-29 15:34
Np, thanks for the quick reply. However, that doesn't seem to help. Do you have a pointer where I could try to debug this? I'm willing to dig in myself, but not entirely sure where to look. What I find confusing is that only nested `Element`s seem to be affected.

**Comment by Demonthos** [comment] 2023-01-29 15:41
I think I found the issue. The issue is not actually related to futures at all, but how we handle drop safety and memorization. The future just causes the re-render that triggers the issue.

When the root component is rerendered it causes the following calls:
```
run_scope: ScopeId(0)
// recurse into all child scopes
ensure_drop_safety(ScopeId(0))
ensure_drop_safety(ScopeId(1))
ensure_drop_safety(ScopeId(4))
ensure_drop_safety(ScopeId(3))
ensure_drop_safety(ScopeId(2))
// ScopeId(1, 2, 4) have borrowed props so they are re-rendered, but ScopeId(3) is memorized and not re-rendered
run_scope: ScopeId(1)
ensure_drop_safety(ScopeId(1))
run_scope: ScopeId(4)
ensure_drop_safety(ScopeId(4))
run_scope: ScopeId(2)
ensure_drop_safety(ScopeId(2))
```

Because ScopeId(3) (the Resize Component) is not re-rendered but has ensure_drop_safety called, the listeners are removed and not replaced which is causing the issue.

**Comment by Demonthos** [comment] 2023-01-29 15:44
Here is a simpler example:
```rust
use dioxus::prelude::*;
use dioxus_desktop::launch;

fn main() {
    launch(App);
}

fn App(cx: Scope) -> Element {
    cx.use_hook(|| {
        cx.needs_update();
    });
    cx.render(rsx! {
        Component{}
    })
}

#[inline_props]
pub fn Component(cx: Scope) -> Element {
    cx.render(rsx!(div {
        width: "100px",
        height: "100px",
        background: "red",
        onclick: |_| { panic!() }
    }))
}
```

**Comment by terhechte** [comment] 2023-01-29 16:14
Thanks, then I'll try the equivalent of forcing a `ResizeComponent` render via:

``` rs
use dioxus::prelude::*;
use dioxus_desktop::launch;

fn main() {
    launch(App);
}

fn App(cx: Scope) -> Element {
    let oo = use_state(cx, || 0);
    cx.use_hook(|| {
        oo.set(*oo.get() + 1);
    });
    cx.render(rsx! {
        Component{
            oo: oo.clone()
        }
    })
}

#[inline_props]
pub fn Component(cx: Scope, oo: UseState<usize>) -> Element {
    let _ = oo.get();
    cx.render(rsx!(div {
        width: "100px",
        height: "100px",
        background: "red",
        onclick: |_| {
            panic!()
        },
        ""
    }))
}

```

or are there better ways to tell the Scope of a child to re-render?

**Comment by terhechte** [comment] 2023-01-29 16:18
Just borrowing the props did the trick. Thanks!

``` rs

#[inline_props]
fn ResizeComponent<'a>(
    cx: Scope<'a>,
    size: &'a UseState<Option<f64>>,
    is_resizing: &'a UseState<bool>,
) -> Element<'a> {
    let class = is_resizing.then(|| "sb-is-resizing").unwrap_or_default();
    cx.render(rsx!(div {
        class: "sb-resize {class}",
        onmousedown: move |_event| {
            is_resizing.set(true);
        },
        onmouseup: move |_event| { is_resizing.set(false) },
        onmouseout: move |event| {
            if *is_resizing.current() == true {
                let value = event.data.page_coordinates().x - 8.;
                size.set(Some(value))
            }
        }
    }))
}
```

**Closed** 2023-01-29 20:08 UTC
Labels: bug, core
