### ISSUE TITLE
use_wry_event_handler logs error when clicking on element

### ISSUE THREAD

**Issue by luveti** [DioxusLabs/dioxus#2566] opened 2024-07-01 02:44 UTC
Given the following code:

```rust
use dioxus::desktop::tao::event::{Event as WryEvent, WindowEvent};
use dioxus::desktop::*;
use dioxus::prelude::*;

fn main() {
    LaunchBuilder::desktop()
        .with_cfg(Config::new().with_close_behaviour(WindowCloseBehaviour::CloseWindow))
        .launch(App)
}

pub fn App() -> Element {
    use_wry_event_handler(move |event, _| {
        if let WryEvent::WindowEvent {
            event:
                WindowEvent::KeyboardInput {
                    device_id,
                    event,
                    is_synthetic,
                    ..
                },
                ..
        } = event
        {
            println!("{device_id:?}, {event:?}, {is_synthetic:?}");
        }
    });

    rsx! {
        div {
            background: "red",
            width: "100vw",
            height: "50vh",
            button {
                onclick: |_| { println!("click"); },
                "Button"
            }
        }
    }
}
```

Clicking on the div / red area logs the following error:

`ERROR dioxus_desktop::app: Error parsing user_event: Error("invalid type: null, expected usize", line: 0, column: 0)`

Clicking outside of the div / on the window does not log an error.

This only occurs when something that accepts events is also on the page (the button in this case).

**Environment:**
 - Dioxus version: git+https://github.com/dioxuslabs/dioxus#d3f96ec32383b5a9b16e109c78a3697a033c0664
 - Rust version: nightly
 - OS info: NixOS
 - App platform: fullstack

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment] 2024-08-19 21:40
Hey! Apparently we aren't serializing events the right way cross-platform. It seems that browsers are not quite standard across platforms in how events propagate.

There's a wonderful table in this issue: https://github.com/DioxusLabs/dioxus/issues/2385

I'm going to close this as a dupe of that and whenever we land a fix for that, we'll make sure this issue gets fixed too.

**Closed by jkelleyrtp** 2024-08-19 21:40 UTC
Labels: bug
