### ISSUE TITLE
Creating project from template seem to write whole template to readme instead of my selected choices

### ISSUE THREAD

**Issue by anvlkv** [DioxusLabs/dioxus#1604] opened 2023-11-03 08:18 UTC
**Problem**

Creating project from template (using cli) seem to write whole template to readme instead of my selected choices

**Steps To Reproduce**

dx create --template gh:dioxuslabs/dioxus-template
[WARN] You appear to be creating a Dioxus project from scratch; we will use the default config
[WARN] Favorite `gh:dioxuslabs/dioxus-template` not found in config, using it as a git repository: https://github.com/dioxuslabs/dioxus-template.git
🤷   Project Name: red-siren
[INFO] 🔧   Destination: /Users/anvlkv/Projects/red-siren ...
[INFO] 🔧   project-name: red-siren ...
[INFO] 🔧   Generating template ...
✔ 🤷   What platform are you targeting? · Fullstack
✔ 🤷   Should the application use the dioxus router? · false
✔ 🤷   What backend framework are you using? · Axum
✔ 🤷   How do you want to create CSS? · Tailwind
[INFO] 🔧   Moving generated files into: `/Users/anvlkv/Projects/red-siren`...
[INFO] 🔧   Initializing a fresh Git repository
[INFO] ✨   Done! New project created /Users/anvlkv/Projects/red-siren
[INFO] Generated project at /Users/anvlkv/Projects/red-siren

**Expected behavior**

```
        # Development
        1. Install npm: https://docs.npmjs.com/downloading-and-installing-node-js-and-npm
        2. Install the tailwind css cli: https://tailwindcss.com/docs/installation
        3. Run the following command in the root of the project to start the tailwind CSS compiler:
        
        ```bash
        npx tailwindcss -i ./input.css -o ./public/tailwind.css --watch
        ```
        
        Launch the Dioxus Fullstack app:
        
        ```bash
        dx build --features web --release
        cargo run --features ssr --release
        ```
```

**Screenshots**

The actual output

```
        # Development
        {% if styling == "Tailwind" %}
        1. Install npm: https://docs.npmjs.com/downloading-and-installing-node-js-and-npm
        2. Install the tailwind css cli: https://tailwindcss.com/docs/installation
        3. Run the following command in the root of the project to start the tailwind CSS compiler:
        
        ```bash
        npx tailwindcss -i ./input.css -o ./public/tailwind.css --watch
        ```
        {% endif %}
        {% if platform == "desktop" %}
        Run the following command in the root of the project to start the Dioxus dev server:
        
        ```bash
        dx serve --hot-reload --platform desktop
        ```
        {% else %}
        {% if platform == "TUI" %}
        Run the following command in the root of the project to start the Dioxus dev server:
        
        ```bash
        dx serve --hot-reload --platform desktop
        ```
        {% else %}
        {% if platform == "web" %}
        Run the following command in the root of the project to start the Dioxus dev server:
        
        ```bash
        dx serve --hot-reload
        ```
        
        - Open the browser to http://localhost:8080
        {% else %}
        {% if platform == "Fullstack" %}
        Launch the Dioxus Fullstack app:
        
        ```bash
        dx build --features web --release
        cargo run --features ssr --release
        ```
        {% else %}
        Launch the Dioxus app:
        
        ```bash
        cargo run
        ```
        {% endif %}
        {% endif %}
```

**Environment:**
 - Dioxus version: 0.4.1
 - Rust version: 1.73.0
 - OS info: MacOS
 - App platform: 'Fullstack'

**Questionnaire**
- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment] 2023-11-03 14:54
(This is a duplicate of https://github.com/DioxusLabs/dioxus-template/issues/7)

https://github.com/DioxusLabs/dioxus-template/pull/11 will fix this issue. @jkelleyrtp could you take a look at that PR when you have the time? I don't have write permissions on the dioxus-template repo, but it does fix the issue in the generated readme

**Closed by ealmloff** 2023-11-03 14:54 UTC
