### ISSUE TITLE
Desktop: The console always opens and does not close when the application is launched.

### ISSUE THREAD

**Issue by RustGrow** [DioxusLabs/dioxus#3152] opened 2024-10-31 17:14 UTC
After creating an application release with the command

```
dx build --release --platform desktop
Successfully built! 💫
Bundle at D:\Rust\dioxus\blog\target\dx\blog\release\windows\app
```

, the console always opens and does not close when the application is launched.

https://github.com/user-attachments/assets/bd48a99b-a227-4f2a-861a-4385b111e4cb

Dioxus version: dioxus 0.6.0-alpha.3 (5d99889)
Rust version: rustc 1.82.0 (f6e511eec 2024-10-15)
OS info: Win11
App platform: desktop

**Comment by ealmloff** [comment] 2024-10-31 19:00
Duplicate of #603 and #1306. You need to enable the windows subsystem as described in the [publishing guide](https://dioxuslabs.com/learn/0.5/cookbook/publishing#preparing-your-application-for-bundling)

**Closed by ealmloff** 2024-10-31 19:00 UTC
