### ISSUE TITLE
Text inside button isn't rendered

### ISSUE THREAD

**Issue by negrel** [DioxusLabs/dioxus#826] opened 2023-02-12 20:07 UTC
**Problem**

Text inside button isn't rendered.

**Steps To Reproduce**

- Compile the following code:
```rust
use dioxus::prelude::*;

pub fn main() {
    dioxus::desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx! {
        button {
            onclick: move |_| {
                println!("hello, desktop!");
                println!("goodbye, desktop!");
            },
            "text"
        }
        p { "another text!" }
    })
}
```

**Expected behavior**

The text "text" should appear inside the button

**Screenshots**

![20230212_20h56m31s_grim](https://user-images.githubusercontent.com/44581623/218333913-f0e38987-131b-4e8b-a05a-199127d5664c.png)

**Environment:**
 - Dioxus version: v0.1.8, `8733be54085a3db24dcd154e384b72c2f4e3f2ad544ebcd7876d1ae07dd9f167`]
 - Rust version: I tried `1.66.1` and `1.69.0-nightly (e84a7928d 2023-01-31)`
 - OS info: `Linux matebook 5.15.93 #1-NixOS SMP Thu Feb 9 10:26:48 UTC 2023 x86_64 GNU/Linux`
 - App platform: `desktop`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

I've tried to reproduce the issue using nix flakes to build the binary. The produced binary that doesn't work on my machine works fine on the other. I don't know where to look at.

**Comment by Demonthos** [comment] 2023-02-12 20:43
This example seems to work on Dioxus 0.3, and the current master version on windows.

The commit you listed does not seem to exist. This dependency fails to resolve:
`dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "8733be54085a3db24dcd154e384b72c2f4e3f2ad544ebcd7876d1ae07dd9f167", features = ["desktop"] }`

If you upgrade to the latest version of Dioxus the example looks like this. Does the issue still appear with the most recent release?
```toml
dioxus-desktop = "0.3"
dioxus = "0.3"
```

```rust

use dioxus::prelude::*;

pub fn main() {
    dioxus_desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx! {
        button {
            onclick: move |_| {
                println!("hello, desktop!");
                println!("goodbye, desktop!");
            },
            "text"
        }
        p { "another text!" }
    })
}
```

**Comment by negrel** [comment] 2023-02-12 21:18
Hi, thanks for your reply.
Yes, I forgot to mention it, it also happens using dioxus 0.3.1

**Comment by pascalbehmenburg** [comment] 2023-12-11 08:10
Using the current master version on macos this works perfectly fine as u can see here:

![image](https://github.com/DioxusLabs/dioxus/assets/26353707/65376cab-3ae8-4a02-9e13-0f987780a6d8)

Therefore you may consider closing that issue.

**Comment by ealmloff** [comment] 2023-12-11 15:16
> Using the current master version on macos this works perfectly fine as u can see here:
> 
> ![image](https://private-user-images.githubusercontent.com/26353707/289466417-65376cab-3ae8-4a02-9e13-0f987780a6d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDY5NzAsIm5iZiI6MTcwMjMwNjY3MCwicGF0aCI6Ii8yNjM1MzcwNy8yODk0NjY0MTctNjUzNzZjYWItM2FlOC00YTAyLTllMTMtMGY5ODc3ODBhNmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE0NTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYzJhZmM1MjliOWU0YTY5NzlkMTdmMTFhNjIwMzYzYWE5OTQ4MzZlMzRlZWJlYWFjNjVmZmY0ZmJjMmM3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OPIMFfCSrjyoFF2yATl3mlZn84HtImszLwGpUDJ72YY)
> 
> Therefore you may consider closing that issue.

The original issue was specific to the system browser installed on nix linux. I could not reproduce this on Ubuntu linux, windows, or mac. It might be a bug with Tauri on nix, or the system browser.

> The produced binary that doesn't work on my machine works fine on the other. I don't know where to look at.

If we cannot reproduce this issue on other devices, it seems more likely that this is something specific to the device like a corrupted installation of the webview. If anyone is able to reproduce this issue, I would be happy to reopen it. The following information would be very helpful:
- Logs from tracing on the trace level
- Any browser errors in the webview console in debug mode
- The HTML that the browser rendered in the webview console

**Closed by ealmloff** 2023-12-11 15:16 UTC
Labels: desktop

**Comment by jkelleyrtp** [comment] 2023-12-11 18:48
It could be the JS engine on this particular system browser is old enough that some modern features we (might) be using cause an exception. We haven't seen it in a while, but it's not impossible for weirder distributions to have out of date web engines.
