### ISSUE TITLE
Form onsubmit doesn't collect selected values

### ISSUE THREAD

**Issue by alexanderjophus** [DioxusLabs/dioxus#1554] opened 2023-10-18 12:53 UTC
**Problem**

When using a form with select, onsubmit and an input button, selecting an option and pressing the button does not submit the option selected.

**Steps To Reproduce**

```rs
#![allow(non_snake_case)]
// import the prelude to get access to the `rsx!` macro and the `Scope` and `Element` types
use dioxus::prelude::*;
use log::{info, LevelFilter};

fn main() {
    dioxus_logger::init(LevelFilter::Info).expect("failed to init logger");
    // launch the web app
    dioxus_web::launch(App);
}

// create a component that renders a div with the text "Hello, world!"
fn App(cx: Scope) -> Element {
    cx.render(rsx! {
        form {
            onsubmit: move |event| {
                info!("submitting form: {event:?}");
            },
            select {
                width: "20%",
                option {
                    value: "notathing",
                    "Select a thing"
                }
                option {
                    value: "thing1",
                    "thing1"
                }
                option {
                    value: "thing2",
                    "thing2"
                }
            }
            input { r#type: "submit", },
        }
    })
}

```

Running the above code, and selecting an option, then press submit.

**Expected behavior**

I'd expect somewhere in the `event` to display the choice.

**Screenshots**

<img width="1296" alt="image" src="https://github.com/DioxusLabs/dioxus/assets/12949385/49dbbec3-af19-4057-9964-eca4f4aab7c7">

**Environment:**
 - Dioxus version: 0.4.0
 - Rust version: 1.72.1
 - OS info: MacOS
 - App platform: web

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by bunnyBites** [comment] 2023-11-04 04:28
I have fixed this issue by following the same syntax as the println!:

So, as per your example, it will be:
 `info!("submitting form: {:?}", event);`

I hope it helped.

**Comment by bunnyBites** [comment] 2023-11-07 03:28
Hi, I have checked this code. The issue is that the select element does not have a "name" property included.

```select {
                width: "20%",
                name: "something", // provide a field name here
                option {
                    value: "notathing",
                    "Select a thing"
                }
                option {
                    value: "thing1",
                    "thing1"
                }
                option {
                    value: "thing2",
                    "thing2"
                }
            }
```

**Comment by ealmloff** [comment] 2023-11-07 14:32
It seems like this isn't actually a bug, so I am closing this issue. If the issue remains after adding a name to the form input, feel free to reopen the issue

**Closed as completed by ealmloff** 2023-11-07 14:32 UTC
Labels: bug, good first issue, web
