### ISSUE TITLE
something wrong when "dx create"

### ISSUE THREAD

**Issue by LitchiInn** [DioxusLabs/dioxus#1354] opened 2023-08-14 02:27 UTC
**Problem**

**Steps To Reproduce**

- dx create
- input project name
- use router choose true
- platform choose web
- CSS choose Tailwind

**Expected behavior**

create project successful

**Screenshots**

![img](https://i.imgur.com/HmfXy2L.png)

**Environment:**
 - Dioxus version: 0.4.1
 - Rust version: 1.70.0
 - OS info: Windows
 - App platform: web

**Questionnaire**
get error when create new project

What should I do?

**Comment by Demonthos** [comment] 2023-08-14 14:29
There is a duplicate log dependency in the template. If you remove the first log crate, it will fix the issue

Closing this as a duplicate of https://github.com/DioxusLabs/dioxus-template/issues/5

**Closed by Demonthos** 2023-08-14 14:29 UTC
