### ISSUE TITLE
error when use dioxus serve

### ISSUE THREAD

**Issue by adezukZ** [DioxusLabs/dioxus#1267] opened 2023-07-30 18:06 UTC
**Problem**
it stop at 
[INFO] 🚅 Running build command...
\ Compiling serde 1.0.178 (registry+https://github.com/rust-lang/crates.io-index)
   Compiling futures-macro v0.3.28
   Compiling serde_derive v1.0.178
\ Compiling num_cpus 1.16.0 (registry+https://github.com/rust-lang/crates.io-index)
   Compiling tokio-macros v2.1.0
\ Compiling fnv 1.0.7 (registry+https://github.com/rust-lang/crates.io-index)
   Compiling mio v0.8.8
/ Compiling fnv 1.0.7 (registry+https://github.com/rust-lang/crates.io-index)
/ Compiling fnv 1.0.7 (registry+https://github.com/rust-lang/crates.io-index)

**Steps To Reproduce**

- 
- 
- 

**Expected behavior**

**Screenshots**

**Environment:**
 - Dioxus version: [e.g. v0.17, `master`]
 - Rust version: [e.g. 1.43.0, `nightly`]
 - rustc 1.71.0
 - OS info: [e.g. windows]
 - App platform: [e.g. `web`, `desktop`]

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment] 2023-07-31 16:05
It looks like you are trying to compile something with tokio as a dependancy. Tokio does not support WASM so this fails. The error not being reported was fixed in https://github.com/DioxusLabs/cli/pull/155, you may need to reinstall the CLI to get that bugfix

**Comment by adezukZ** [comment] 2023-07-31 18:54
> It looks like you are trying to compile something with tokio as a dependancy. Tokio does not support WASM so this fails. The error not being reported was fixed in [DioxusLabs/cli#155](https://github.com/DioxusLabs/cli/pull/155), you may need to reinstall the CLI to get that bugfix

I have install the day I created this issue

**Comment by Demonthos** [comment] 2023-07-31 21:29
The dioxus CLI now lives in the main dioxus repo, you can install the nightly version with:
```sh
cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli
```

**Comment by adezukZ** [comment] 2023-08-01 04:52
> The dioxus CLI now lives in the main dioxus repo, you can install the nightly version with:
> 
> ```shell
> cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli
> ```

dioxus serve --release
[INFO] 🚅 Running build command...
\ Compiling serde 1.0.178 (registry+https://github.com/rust-lang/crates.io-index)
   Compiling futures-macro v0.3.28
   Compiling serde_derive v1.0.178
- Compiling tokio 1.29.1 (registry+https://github.com/rust-lang/crates.io-index)
   Compiling tokio-macros v2.1.0
   Compiling thiserror v1.0.44
/ Compiling num_cpus 1.16.0 (registry+https://github.com/rust-lang/crates.io-index)
/ Compiling thiserror 1.0.44 (registry+https://github.com/rust-lang/crates.io-index)
| Compiling thiserror 1.0.44 (registry+https://github.com/rust-lang/crates.io-index)
mio v0.8.8
\ Compiling thiserror 1.0.44 (registry+https://github.com/rust-lang/crates.io-index)
- Compiling thiserror 1.0.44 (registry+https://github.com/rust-lang/crates.io-index)
- Compiling thiserror 1.0.44 (registry+https://github.com/rust-lang/crates.io-index)

**Comment by Demonthos** [comment] 2023-08-02 16:16
Dioxus has been renamed dx, so the new command is `dx serve --release`, `dioxus serve --releasew will use the old version of dioxus you have installed. I tried compiling a blank project with tokio added, and it did report an error.

<img width="1167" alt="Screenshot 2023-08-02 at 9 13 51 AM" src="https://github.com/DioxusLabs/dioxus/assets/66571940/68f7501d-9154-4612-b2c5-828e52449dda">


If you have time, a reproducible repo with the dependancies you found caused dioxus to loop instead of showing an error would be very helpful tracking down this issue.

Until this issue is fixed, `cargo check --target wasm32-unknown-unknown` should show you the real error.

**Closed** 2023-08-08 00:20 UTC
