### ISSUE TITLE
Wrong API in dioxus-web mounted.rs

### ISSUE THREAD

**Issue by magikmw** [DioxusLabs/dioxus#3265] opened 2024-12-01 15:33 UTC
**Problem**

When compiling a dioxus 0.6.0-alpha5:

```
16:22:26 [cargo] error[E0599]: no method named `set_behavior` found for struct `ScrollIntoViewOptions` in the current scope
  --> /home/magikmw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-web-0.6.0-alpha.5/src/events/mounted.rs:74:25
   |
74 |                 options.set_behavior(web_sys::ScrollBehavior::Instant);
   |                         ^^^^^^^^^^^^
   |
help: there is a method `behavior` with a similar name
   |
74 |                 options.behavior(web_sys::ScrollBehavior::Instant);
   |                         ~~~~~~~~

16:22:26 [cargo] error[E0599]: no method named `set_behavior` found for struct `ScrollIntoViewOptions` in the current scope
  --> /home/magikmw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-web-0.6.0-alpha.5/src/events/mounted.rs:77:25
   |
77 |                 options.set_behavior(web_sys::ScrollBehavior::Smooth);
   |                         ^^^^^^^^^^^^
   |
help: there is a method `behavior` with a similar name
   |
77 |                 options.behavior(web_sys::ScrollBehavior::Smooth);
   |                         ~~~~~~~~
```

**Steps To Reproduce**

- point Cargo.toml to alpha-5
- try dx serve
- see above error

**Expected behavior**

Should build and run.

**Screenshots**

**Environment:**
 - Dioxus version:   0.6.0-alpha5 (cli and in Cargo.toml)
 - Rust version:     1.83.0
 - OS info:          - Fedora Linux 40
 - App platform:     fullstack

**Questionnaire**

**Comment by ealmloff** [comment] 2024-12-01 22:14
Closing as duplicate of https://github.com/DioxusLabs/dioxus/issues/3197

**Closed by ealmloff** 2024-12-01 22:14 UTC
