### ISSUE TITLE
The oninput event of input textarea cannot monitor Chinese input method input and clipboard paste

### ISSUE THREAD

**Issue by WZY1999428** [DioxusLabs/dioxus#3454] opened 2024-12-26 02:17 UTC
**Problem**

When I use duoxus to write a Windows client, I use input textarea. When I input Chinese input method and paste on the clipboard, the oninput event cannot be triggered, causing use_signal to fail to update the value.

**Steps To Reproduce**

  let mut value1=use_signal(||String::new());
    let mut value2=use_signal(||String::new());
    rsx! {
        document::Link { rel: "stylesheet", href: MAIN_CSS }
        document::Link { rel: "stylesheet", href: ICONFONT_CSS }
        body{
          oncontextmenu: move |e| e.prevent_default(),
          div {
            class: "container",
            input{
                value:value1.read().clone(),
                oninput: move |e|  {
                    value1.set(e.value());
                    println!("{:?}",e.value());
                }
            }
            textarea { 
              value:value2.read().clone(),
             oninput: move |e| {
                value2.set(e.value());
                println!("{:?}",e.value());
             }
             }
           }
        }
    }

- 
- 
- 

**Screenshots**

https://github.com/user-attachments/assets/6d294f55-3edd-4ff8-9734-af708dd01e85

**Environment:**
 - Dioxus version: 0.6.1
 - Rust version:     1.82.0
 - OS info:        Windows
 - App platform:    desktop

**Comment by tdomhan** [comment] 2024-12-27 14:29
This might be a duplicate of: https://github.com/DioxusLabs/dioxus/issues/3125

**Comment by WZY1999428** [comment] 2024-12-27 15:45
It should be the same, then I will close this question

**Closed** 2024-12-27 15:45 UTC
