### ISSUE TITLE
Dioxus DevTools

### ISSUE THREAD

**Issue by itsezc** [DioxusLabs/dioxus#2659] opened 2024-07-20 07:09 UTC
## Feature Request

A Chrome / Firefox / Safari extension to help build Dioxus apps, which helps with: tracking signals, state, routing etc. This is one of the biggest factors that stops developers from picking up Dioxus / rust based web frameworks, lack of dev tooling and support. A great example to compare to would be Nuxt's DevTools: https://devtools.nuxt.com/

If we can craft an experience similar to that, it would help aid adoption of Dioxus and increase productivity with it significantly

**Comment by ealmloff** [comment] 2024-07-20 16:14
Duplicate of #198

**Closed by ealmloff** 2024-07-20 16:14 UTC
