### ISSUE TITLE
Hot reload with tailwind css is unstable and requires manual reloading

### ISSUE THREAD

**Issue by Protoculos** [DioxusLabs/dioxus#1663] opened 2023-11-26 13:07 UTC
Specific Demand

I need a feature that will allow me to use hot reload with tailwind css without having to manually restart the dx serve --hot-reload command and the browser. This will improve my development experience and the quality of my video tutorials.

Implement Suggestion

I don’t know how to implement this feature, but maybe you can look into how tailwind css works with other frameworks that support hot reload, such as React or Vue. Maybe there is a way to integrate tailwind css with dioxus more seamlessly and efficiently.

https://github.com/DioxusLabs/dioxus/assets/9038676/19346ce4-abd7-4577-a477-573981d75cf9

**Comment by ealmloff** [comment] 2023-11-26 13:49
Tailwind integration could be a plugin. The plugin system was started in https://github.com/DioxusLabs/cli/pull/124, but we now plan to use WIT + WASI to define plugins in Rust

**Comment by dawkaka** [comment] 2023-11-27 18:08
hot reload doesn't. work at all for me. How did you get it to work
```
cannot find function `init` in crate `dioxus_hot_reload`
not found in `dioxus_hot_reload`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B0%5D?0#file%3A%2F%2F%2Fhome%2Fdawkaka%2Fprojects%2Fapi-workflows%2Fsrc%2Fmain.rs)
lib.rs(53, 28): Actual error occurred here
main.rs(5, 1): consider importing one of these items: `use dioxus_logger::init;
`, `use env_logger::init;
`
failed to resolve: could not find `Config` in `dioxus_hot_reload`
could not find `Config` in `dioxus_hot_reload`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B2%5D?2#file%3A%2F%2F%2Fhome%2Fdawkaka%2Fprojects%2Fapi-workflows%2Fsrc%2Fmain.rs)
lib.rs(53, 52): Actual error occurred here
main.rs(5, 1): consider importing this struct: `use dioxus_desktop::Config;
```

**Comment by ealmloff** [comment] 2023-11-28 23:54
Closing this as a duplicate of https://github.com/DioxusLabs/dioxus/issues/1192

**Closed by ealmloff** 2023-11-28 23:54 UTC
Labels: enhancement, cli
